export enum AgreementStatus {
  DRAFT = 'DRAFT',
  // CREATED = 'CREATED',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
  APPROVED = 'APPROVED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
  SENT_FOR_SIGNATURE = 'SENT_FOR_SIGNATURE',
  SIGNER_REJECTED = 'SIGNER_REJECTED',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
  REJECTED = 'REJECTED',
  ERROR = 'ERROR',
}
export enum TemplateStatus {
  DRAFT = 'DRAFT',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
  APPROVED = 'APPROVED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
}
export enum ClauseStatus {
  DRAFT = 'DRAFT',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
  APPROVED = 'APPROVED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
}
export enum DisplayMode {
  CREATE = 'CREATE',
  VIEW = 'VIEW',
  UPDATE = 'UPDATE',
}
export enum SignatoryStatus {
  WAITING = 'WAITING',
  SIGNED = 'SIGNED',
  REJECTED = 'REJECTED',
}
