# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  contractmanager-app:
    image: contractmanager
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://contractmanager-mongodb:27017/?waitQueueMultiple=1000
#      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@contractmanager-mongodb:27017/?waitQueueMultiple=1000
#      - mongodb://admin:password@127.0.0.1:27017/contractmanager?readPreference=primary&directConnection=true&ssl=false&authMechanism=DEFAULT
      - SPRING_DATA_MONGODB_DATABASE=contractmanager
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
#      - 127.0.0.1:8080:8080
#      - 80:8080
#       - 443:8085
      - 80:8085
    volumes:
       - ~/volumes/docker/contractmanager/temp:/src/main/webapp/content/
       - ~/volumes/docker/contractmanager/config/adobe:/src/main/resources/config/adobe
  contractmanager-mongodb:
    image: mongo:4.4.6
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: password
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
#     - 127.0.0.1:27017:27017
      - 27017:27017
    volumes:
      - ~/volumes/jhipster/contractmanager/mongodb/:/data/db/
#      - /home/ubuntu/volumes/data/db/mongo:/data/db/
