pipeline {
  agent any
  // tools {
	//     maven "Maven3"
	//     jdk "OpenJDK11"
  //     nodejs 'NodeJs18'
	// }
  environment {
        registryCredential = 'ecr:us-east-1:awscreds'
        appRegistry = "603964211152.dkr.ecr.us-east-1.amazonaws.com/contractmanager"
        vprofileRegistry = "https://603964211152.dkr.ecr.us-east-1.amazonaws.com"
    }
  stages {
    stage('Fetch code'){
      steps {
        git branch: 'main', url: 'https://github.com/vineeshst/contractmanager_1.0.git'
      }
    }
    stage('Install Custom jars'){
      steps {
        sh 'mvn install:install-file -Dfile=/var/lib/adobe-sign-1.2.0.jar -DgroupId=com.adobe.sign -DartifactId=adobe-sign -Dversion=1.2.0 -Dpackaging=jar'
      }
    }
    // stage('Test'){
    //   steps {
    //     sh 'mvn test'
    //   }
    // }
    stage ('Build docker image') {
      steps {
          sh 'mvn package -Pprod verify jib:dockerBuild -DskipTests'
            }
        }

    stage('Upload App Image') {
          steps{
            script {
              docker.withRegistry( vprofileRegistry, registryCredential ) {
                docker.image("contractmanager").push("latest")
              }
            }
          }
     }
  }

}
